# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevoteeParentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('mother_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevoteesMaterialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('marital_status', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('time_of_birth', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('current_address', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('Profession', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevoteesServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preaching', models.CharField(max_length=100, null=True)),
                ('services', models.CharField(max_length=100, null=True)),
                ('leader', models.TextField(null=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesMaterialInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DevoteesSpiritualInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiritual_name', models.CharField(max_length=200, null=True)),
                ('diksha_guru', models.CharField(max_length=200, null=True)),
                ('diksha_date', models.DateTimeField(default=None, null=True)),
                ('diksha_place', models.CharField(max_length=200, null=True)),
                ('brahman', models.BooleanField(default=0)),
                ('shiksha_level', models.CharField(max_length=100, null=True)),
                ('chanting_rounds', models.IntegerField(default=0)),
                ('courses', models.CharField(max_length=100, null=True)),
                ('shiksha_guru', models.CharField(max_length=200, null=True)),
                ('life_member', models.CharField(max_length=50, null=True)),
                ('donor_number', models.CharField(max_length=50, null=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesMaterialInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DevoteesSpouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('time_of_birth', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('Profession', models.TextField(null=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesMaterialInfo')),
                ('service_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesServiceInfo')),
                ('spiritual_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesSpiritualInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DevotessChildrenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('marital_status', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('time_of_birth', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('Profession', models.TextField(null=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesMaterialInfo')),
                ('service_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesServiceInfo')),
                ('spiritual_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesSpiritualInfo')),
            ],
        ),
        migrations.AddField(
            model_name='devoteeparentinfo',
            name='devotee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devotees_info.DevoteesMaterialInfo'),
        ),
        migrations.AddField(
            model_name='devoteeparentinfo',
            name='father_service_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_service_info', to='devotees_info.DevoteesServiceInfo'),
        ),
        migrations.AddField(
            model_name='devoteeparentinfo',
            name='father_spiritual_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_spiritual_info', to='devotees_info.DevoteesSpiritualInfo'),
        ),
        migrations.AddField(
            model_name='devoteeparentinfo',
            name='mother_service_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_service_info', to='devotees_info.DevoteesServiceInfo'),
        ),
        migrations.AddField(
            model_name='devoteeparentinfo',
            name='mother_spiritual_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_spiritual_info', to='devotees_info.DevoteesSpiritualInfo'),
        ),
    ]
