# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees_info', '0002_auto_20160604_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoteesmaterialinfo',
            name='date_of_birth',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
